### ISSUE TITLE
Suggestion: Clean up of expired cache items

### ISSUE THREAD

**Issue by wlkns** [terrylinooo/simple-cache#2]
Great library, can certainly see myself using this outside of a framework.

I think it would benefit from a "clean up" (not clear) for removing expired but not deleted items. The purpose being that sometimes you want to purge the cache of expired items, but you don't want to fully clear it, as perhaps the cache has resource intensive items such as generated thumbnails.

Little pushed on time at the moment, but happy to submit a PR too if you like the idea. And apologies if this is not the correct place for suggestions.

**Comment by terrylinooo** [comment]
Hello, this library  is an implementation of [Psr\SimpleCache\CacheInterface](https://www.php-fig.org/psr/psr-16/) so only has the public methods defined in PSR-16 for now. 

Most of the memory-type cache architectures such as Redis, Memcached and others, will automatically remove expired items so that PSR-16 does not has a method for that.

Your suggestions are very good for non-memory drivers, I'll make it in the next update.

Thanks for your suggestions.

**Comment by terrylinooo** [comment]
`clearExpiredItems` is added in 1.3.0
